version: "3.3"

services:
  cuben:
    container_name: cuben
    restart: always
    image: node:20.10.0
    ports:
      - 4001:5007
    volumes:
      - ./:/usr/src/cuben
    working_dir: /usr/src/cuben
    
    networks:
      - monorepo-network

    # FOR PRODUCTION 
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  cuben-batch:
    container_name: cuben-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:5008
    volumes:
      - ./:/usr/src/cuben
    working_dir: /usr/src/cuben
    
    networks:
      - monorepo-network

    # FOR PRODUCTION 
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

  
networks:
  monorepo-network:
    driver: bridge